//APP Action
export const APP_LOGIN = 'APP_LOGIN'
export const APP_LOGOUT = 'APP_LOGOUT'

//Home Action
export const HOME_GET_API = 'HOME_GET_API'
export const TOURS_GET_API_SUCCESS = 'TOURS_GET_API_SUCCESS'
export const UPDATE_PROGRESS_UPLOAD = 'UPDATE_PROGRESS_UPLOAD'